### ISSUE TITLE
How to download MSR-VTT datatset?

### ISSUE THREAD

**Issue by KyeonghaRho** [YuanGongND/cav-mae#11]
Hi, I like your marvelous work including a large number of experiments.
I'm working on a project based on your work, and I want to ask you a question.
You reported the training and zero-shot retrieval results on MSR-VTT dataset.
However, I cannot find any github or link for downloading the dataset.
So may I ask how to download MSR-VTT dataset, and how did you preprocess it? (is there any github code that you referred to?)
Thank you.

-Kyeongha

**Comment by YuanGongND** [comment]
Hi there, 

thanks for the question. I got the data from my colleague, so I am not sure how it is downloaded. 

But it seems MSR-VTT is a commonly used dataset, a quick Google search found this: https://www.kaggle.com/datasets/vishnutheepb/msrvtt (note: we do not download data from this link, different data sources may cause performance difference).

-Yuan

**Comment by KyeonghaRho** [comment]
Dear Yuan,
I really appreciate your kind answer.
I already checked the link before asking you the question, but if I'm not wrong, the link provides only the train/val set, not including the test set.
Would you mind if I earnestly plead with you to share the MSR-VTT test set and preprocessing code?

-Kyeongha

**Comment by YuanGongND** [comment]
Unfortunately, we cannot re-release the data. You may ask the authors of MSR-VTT for that.

**Comment by KyeonghaRho** [comment]
Oh, I see. I will ask the authors of MSR-VTT for that. Thanks for your advice.
