### ISSUE TITLE
retrieval evaluation

### ISSUE THREAD

**Issue by sukun1045** [YuanGongND/cav-mae#15]
Hi, just want to make sure I understand it correctly. Based on the `retrieval.py`, only the middle frame (`frame_use = 5`) of the video will be used. Do I understand it correctly?

Also, I am wondering what is the reason for using the [for loop](https://github.com/YuanGongND/cav-mae/blob/cd810cb54c020bcc1afbebaf2a57876e02ed6f7b/src/retrieval.py#L32) to compute the similarity one by one? It turns out to be very slow. Can we just do something similar to the [CLIP zero shot retrieval](https://github.com/LAION-AI/CLIP_benchmark/blob/567f01c655514f5f3caaea55d73d2c946f6bc1a1/clip_benchmark/metrics/zeroshot_retrieval.py#L96)? I tried both implementation and the result looks same to me but much faster.

**Comment by YuanGongND** [comment]
Hi there,

This is just for easy understanding (i.e., explicitly show the algorithm without calling an external package), you can use any efficient algorithm if the result is the same. 

-Yuan

**Comment by sukun1045** [comment]
Sure. But with a more efficient algorithm, does it make sense to conduct the retrieval evaluation from the whole test set instead of 5 samples per class?

**Comment by YuanGongND** [comment]
Yes, but the number will be lower as the task is harder with more samples in the pool. Also, you would need to consider the class balance issue.
