### ISSUE TITLE
Question Regarding stat calculation of dataset

### ISSUE THREAD

**Issue by ben2002chou** [YuanGongND/cav-mae#24]
https://github.com/YuanGongND/cav-mae/blob/68fe8c2a3917dc2926e41f796bfdcb331a64b42c/src/dataloader.py#L87-L96

Hello, I would like some help regarding how can I get norm and std stats from audioset. I see this code here has some purpose in getting normalization stats, but it isn't very clear to me how I can get normalization stats following the comments.

**Comment by YuanGongND** [comment]
For Audioset, please just use our stats for both audio and image. 

For other datasets, I believe it is also OK to use our stats unless it is really out of the domain (e.g., biomedical image).

-Yuan

**Comment by YuanGongND** [comment]
In you are interested in how it is calculated, please check https://github.com/YuanGongND/ast/blob/master/src/get_norm_stats.py

**Comment by ben2002chou** [comment]
Thank you!
